# Generated by Django 3.1 on 2020-09-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200725_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mymomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Yves Byiringiro', max_length=30)),
                ('number', models.CharField(default='0781 433 445', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(default='078 000 0000', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.AddField(
            model_name='product',
            name='filter',
            field=models.CharField(blank=True, help_text='Enter: men , women , kid , accessories , cosmetic', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='not specified', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Shoes', 'Shoes'), ('Sutes', 'Sutes'), ('Clothes', 'Clothes'), ('Shirts', 'Shirts'), ('TShirts', 'TShirts'), ('Jeans', 'Jeans'), ('Phones', 'Phones'), ('Laptops', 'Laptops')], default='Shoes', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, default='0781607266', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Silver', 'Silver'), ('Gray', 'Gray'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Dark blue', 'Dark blue'), ('Light blue', 'Light blue'), ('Black and white', 'Black and white'), ('Gold', 'Gold'), ('Not Specified', 'Not Specified')], default='Black', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_minutes',
            field=models.CharField(default='2 hours', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.seller'),
        ),
    ]
