# Generated by Django 2.2.12 on 2020-10-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200930_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='operation_fee',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_fee',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Silver', 'Silver'), ('Gray', 'Gray'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Greenn', 'Green'), ('Dark blue', 'Dark blue'), ('Light blue', 'Light blue'), ('Black and white', 'Black and white'), ('Gold', 'Gold'), ('Not Specified', 'Not Specified'), ('All colors', 'All  colors')], default='Black', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Shoes', 'Shoes'), ('Sutes', 'Sutes'), ('Clothes', 'Clothes'), ('Shirts', 'Shirts'), ('TShirts', 'TShirts'), ('Jeans', 'Jeans'), ('Handbags', 'Handbags'), ('Dresses', 'Dresses'), ('Phones', 'Phones'), ('Laptops', 'Laptops'), ('Headsets', 'Headsets'), ('Speakers', 'Speakers')], default='Shoes', max_length=200, null=True),
        ),
    ]
