# Generated by Django 2.2.12 on 2020-10-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201010_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
