# Generated by Django 2.2.12 on 2020-10-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201010_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Silver', 'Silver'), ('Gray', 'Gray'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Greenn', 'Green'), ('Dark blue', 'Dark blue'), ('Light blue', 'Light blue'), ('Black and white', 'Black and white'), ('Gold', 'Gold'), ('N/S', 'N/S'), ('All colors', 'All  colors')], default='Black', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_minutes',
            field=models.CharField(default='12 days', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='N/S', max_length=50, null=True),
        ),
    ]
