# Generated by Django 2.2.12 on 2020-10-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201010_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, default=2500, max_digits=10),
            preserve_default=False,
        ),
    ]
