# Generated by Django 3.0.8 on 2020-07-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_momotranctionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='momotranctionid',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
