# Generated by Django 3.0.8 on 2020-07-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200726_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymomo',
            name='name',
            field=models.CharField(default='Yves Byiringiro', max_length=30),
        ),
        migrations.AlterField(
            model_name='mymomo',
            name='number',
            field=models.CharField(default='0781607266', max_length=13),
        ),
    ]
