# Generated by Django 3.0.8 on 2020-07-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200726_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_dollar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
