# Generated by Django 3.0.8 on 2020-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200729_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_minutes',
            field=models.CharField(default='45 Minutes', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True),
        ),
    ]
