# Generated by Django 3.0.8 on 2020-07-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200729_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7, null=True),
        ),
    ]
