# Generated by Django 3.0.8 on 2020-07-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200730_1014'),
        ('store', '0014_auto_20200729_1243'),
    ]

    operations = [
    ]
