# Generated by Django 3.0.8 on 2020-07-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200730_1507'),
        ('store', '0017_merge_20200730_1127'),
    ]

    operations = [
    ]
