# Generated by Django 3.0.9 on 2020-08-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200803_1409'),
        ('store', '0018_merge_20200731_0851'),
    ]

    operations = [
    ]
