# Generated by Django 3.0.8 on 2020-08-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200817_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter',
            field=models.CharField(blank=True, help_text='Enter: men , women , kid , accessories , cosmetic', max_length=50, null=True),
        ),
    ]
