# Generated by Django 2.2.12 on 2020-08-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Sneakers', 'Sneakers'), ('Derby', 'Derby'), ('Boots', 'Boots'), ('Sandals', 'Sandals'), ('Sutes', 'Sutes'), ('Shirts', 'Shirts'), ('TShirts', 'TShirts'), ('Jeans', 'Jeans')], default='Sneakers', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
