# Generated by Django 2.2.12 on 2020-08-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20200824_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Shoes', 'Shoes'), ('Sutes', 'Sutes'), ('Shirts', 'Shirts'), ('TShirts', 'TShirts'), ('Jeans', 'Jeans'), ('Phones', 'Phones'), ('Laptops', 'Laptops')], default='Shoes', max_length=200, null=True),
        ),
    ]
