# Generated by Django 3.0.9 on 2020-08-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_merge_20200803_1420'),
        ('store', '0025_auto_20200824_1133'),
    ]

    operations = [
    ]
