# Generated by Django 2.2.12 on 2020-08-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20200824_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Silver', 'Silver'), ('Gray', 'Gray'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Dark blue', 'Dark blue'), ('Gold', 'Gold')], default='Black', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_minutes',
            field=models.CharField(default='2 hours', max_length=50),
        ),
    ]
