# Generated by Django 2.2.12 on 2020-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20200825_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Silver', 'Silver'), ('Gray', 'Gray'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Dark blue', 'Dark blue'), ('Light blue', 'Light blue'), ('Black and white', 'Black and white'), ('Gold', 'Gold'), ('Not Specified', 'Not Specified')], default='Black', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Shoes', 'Shoes'), ('Sutes', 'Sutes'), ('Clothes', 'Clothes'), ('Shirts', 'Shirts'), ('TShirts', 'TShirts'), ('Jeans', 'Jeans'), ('Phones', 'Phones'), ('Laptops', 'Laptops')], default='Shoes', max_length=200, null=True),
        ),
    ]
