# Generated by Django 3.0.9 on 2020-08-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_merge_20200824_1525'),
        ('store', '0026_auto_20200825_1414'),
    ]

    operations = [
    ]
