# Generated by Django 3.0.9 on 2020-08-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_merge_20200825_1422'),
        ('store', '0027_auto_20200825_1836'),
    ]

    operations = [
    ]
