# Generated by Django 2.2.12 on 2020-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20200831_0600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MomoTranctionID',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='by@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(default='j', max_length=200),
            preserve_default=False,
        ),
    ]
