# Generated by Django 3.1 on 2020-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_product_available_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_size',
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
