# Generated by Django 3.1 on 2020-09-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20200906_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momotranctionid',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
