# Generated by Django 3.0.9 on 2020-09-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20200901_0452'),
        ('store', '0028_merge_20200825_1839'),
    ]

    operations = [
    ]
