# Generated by Django 3.0.9 on 2020-09-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_merge_20200901_2118'),
        ('store', '0033_auto_20200904_1825'),
    ]

    operations = [
    ]
