# Generated by Django 3.1 on 2020-09-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20200908_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momotranctionid',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
