# Generated by Django 3.0.9 on 2020-09-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_merge_20200904_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
