# Generated by Django 3.0.9 on 2020-09-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20200904_1841'),
        ('store', '0035_auto_20200904_1831'),
    ]

    operations = [
    ]
