# Generated by Django 2.2.12 on 2020-09-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, default='0781607266', max_length=12, null=True),
        ),
    ]
