# Generated by Django 3.0.8 on 2020-07-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=600)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='carousels')),
                ('animation', models.CharField(blank=True, help_text='Enter: fadeInDown    zoomInLeft  zoomInRight', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=600)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='carousels')),
                ('animation', models.CharField(blank=True, help_text='Enter: fadeInDown   zoomInLeft   zoomInRight', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=500)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
