# Generated by Django 3.1 on 2020-09-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveCarousel',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
